module("Date Validation", {
    setup: function(){
        var f = jasmine.getFixtures();
        f.fixturesPath = 'base';
        f.load('screens/DateValidation.html');
    },
    teardown: function() {
        var f = jasmine.getFixtures();
        f.cleanUp();
        f.clearCache();
    }
});
   var rules = new Object(),
             options = new Object(),
             i=0;
         //options.allrules = $.validationEngineLanguage.allRules;
         options.allrules = {};
	
test("Rule : DAT00003", function() {

		//var input = $("input")[0];
        var field = $('#date1');
         rules = ["","DAT00003"];

         field.val("1212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"1212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"0909","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("12121");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("12.9.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"1209","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2.12.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"0212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.7.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"3107","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"3006","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         
         field.val("1209");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"1209","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("0212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"0212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("3107");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"3107","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("3006");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"3006","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2902");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("3212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("1213");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });
test("Rule : DAT00004", function() {
		//var input = $("input")[0];
        var field = $('#date2');
         rules = ["","DAT00004"];
         
         field.val("121212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"121212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"090912","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("12.12.00");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"121200","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.2");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("12121");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12.12.1");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("321200");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("121312");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  

 
         field.val("12.9.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"120912","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2.12.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"021212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.7.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"310712","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"300612","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29.2.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"290212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         
         field.val("120912");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"120912","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("021212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"021212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("310712");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"310712","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("300612");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"300612","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("290213");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("290212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"290212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         

         field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });
test("Rule : DAT00005", function() {
		//var input = $("input")[0];
        var field = $('#date3');
         rules = ["","DAT00005"];
         
         field.val("12121212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12121212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("111100");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"11112000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09092012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("1.1.1200");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"01011200","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 

         field.val("9.9.2");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12121");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12.12.1");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("32122000");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12131200");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
          
         // EIN=(TTMMJJJJ,TTMMJJ,T.M.JJ,T.M.JJJJ),AUS='TTMMJJJJ'
         field.val("12.9.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12091950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2.12.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02121950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.7.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31071950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30061950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.99");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30061999","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.00");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30062000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         
         field.val("12.9.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12092012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2.12.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02122012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.7.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31072012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30062012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29.2.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"29022012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         
         field.val("120912");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12092012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("021212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02122012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("310712");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31072012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("300612");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30062012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("290213");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("290212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"29022012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         
         field.val("12091950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12091950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02121950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02121950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31071950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31071950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30061950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30061950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29021950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29022012");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"29022012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
   
        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });

 	test("Rule : DAT00006", function() {
 		//var input = $("input")[0];
        var field = $('#date4');
         rules = ["","DAT00006"];
         
         field.val("1212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"1212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"0912","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("09.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"0912","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("12.01");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"1201","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("112");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("9.200");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("9.1");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12121");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("1300");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("100");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });
test("Rule : DAT00008", function() {
 		//var input = $("input")[0];
        var field = $('#date5');
         rules = ["","DAT00008"];
         
         field.val("02.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02.99");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.1999","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02.00");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.2000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("2.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("09.1212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09.1212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02.1950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02.1999");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.1999","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02.2000");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.2000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("11.2");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("9.200");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("121211");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("13.00");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });
 	test("Rule : DAT00013", function() {
 		//var input = $("input")[0];
        var field = $('#date7');
         rules = ["","DAT00013"];
         
         field.val("0212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.12.","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("0213");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.8.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09.08.","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("09.08.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09.08.","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.12.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09.12.","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.9.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.09.","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("112");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("7.7");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("5.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12.5");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
		   field.val("3312");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
		   field.val("9.13.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("32.7.");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });


 	test("Rule : DAT00007", function() {
 		//var input = $("input")[0];
        var field = $('#date10');
         rules = ["","DAT00007"];
         
         field.val("2/12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02/2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9/1990");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09/1990","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("09/1990");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09/1990","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("10/00");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"10/2000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString"));  
         field.val("07/13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"07/2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString"));  
         field.val("08/13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("10/99");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"10/1999","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString"));  
         field.val("08/89");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("10/2000");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"10/2000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString"));  
         field.val("07/2013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"07/2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString"));  
         field.val("08/2013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("08/1989");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("10/1999");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"10/1999","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString"));  
         field.val("10/001");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("9/1212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange ,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("5/2014");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange ,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  

        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });

 	test("Rule : DAT00009", function() {
 		//var input = $("input")[0];
        var field = $('#date8');
         rules = ["","DAT00009"];
         field.val("12121212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.12.1212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("111100");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"11.11.2000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09.09.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("1.1.2013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"01.01.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.2");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12122014");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12.12.1");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("32122000");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
		   field.val("12131200");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  

         field.val("12.9.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2.12.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.12.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.7.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31.07.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.06.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.99");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.06.1999","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.00");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.06.2000","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         
         field.val("12.9.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("2.12.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.12.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.7.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31.07.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.06.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29.2.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"29.02.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         
         field.val("120912");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("021212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.12.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("310712");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31.07.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("300612");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.06.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("290213");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("290212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"29.02.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         
         field.val("12091950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02121950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.12.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31071950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31.07.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30061950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.06.1950","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29021950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29022012");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"29.02.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
  
        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });
    test("Rule : DAT00011", function() {
 		//var input = $("input")[0];
        var field = $('#date9');
         rules = ["","DAT00011"];
         field.val("12092013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("120913");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09.09.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.2013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"09.09.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("9.9.2");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12122014");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12.12.1");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("32122000");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
		   field.val("12131200");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  

         field.val("12.9.50");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("2.12.14");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("31.7.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("30.6.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("30.6.14");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("30.6.00");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29.2.12");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         
         field.val("12.12.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.12.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.8.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31.08.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.13");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
           
         field.val("120913");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("021213");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.12.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("310712");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("300612");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("290213");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("290212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         
         field.val("12092013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.09.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("02122013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"02.12.2013","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31071950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("30062014");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29021950");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("29022012");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertTextRange,"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
 
        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });


 	test("Rule : DAT00012", function() {
 		////var input = $("input")[0];
        var field = $('#date6');
         rules = ["","DAT00012"];
         field.val("12121212");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.12.1212","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("1.1.1100");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"01.01.1100","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("1.12.1100");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"01.12.1100","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("12.1.1100");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.01.1100","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("12.12.1100");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"12.12.1100","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("01.12.1201");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"01.12.1201","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("30.6.1201");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"30.06.1201","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("31.7.1201");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"31.07.1201","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.2012");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultString"),"29.02.2012","Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultString")); 
         field.val("29.2.2013");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText")); 
         field.val("9.9.2");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12121");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("12.12.1");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
         field.val("32.12.2000");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
		   field.val("12.13.2000");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));  
        field.val("1a");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         field.val("#(");
         $.methodDate(field, rules, i, options);
         equal(jQuery.data(field,"resultErrorText"),options.allrules[rules[1]].alertText + ' ' + (options.allrules[rules[1]].dateFormat+'').replace(/,/g," or "),"Input : "+field.val()+ ", Result : "+jQuery.data(field,"resultErrorText"));
         });

